apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  ports:
  - name: http
    port: 85
    protocol: TCP
  selector:
    app: nginx-jenkins
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-jenkins
  name: nginx-jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-jenkins
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-jenkins
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
